# Generated by Django 3.2.6 on 2021-08-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Desenvolvimento', 'Development'), ('Atendimento', 'Service'), ('Manutenção', 'Maintenance'), ('Manutenção Urgente', 'Urgent Maintenance')], max_length=50),
        ),
    ]
